# Generated by Django 5.0.6 on 2024-05-31 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("subj", "Subjective"),
                            ("ext", "Extended Awareness"),
                            ("contx", "Contextual"),
                            ("cltr", "Culture"),
                            ("idty", "Identity"),
                        ],
                        max_length=200,
                    ),
                ),
                ("about", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("text", models.TextField(default="")),
                ("notes", models.TextField(default="")),
                ("date_made", models.DateField(auto_now_add=True)),
                ("share", models.BooleanField(default=False)),
                ("component", models.ManyToManyField(to="techniques_app.component")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
