# Generated by Django 5.0.6 on 2024-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techniques_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="stared",
            field=models.BooleanField(default=False),
        ),
    ]
