# Generated by Django 5.0.6 on 2024-06-17 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techniques_app", "0003_remove_technique_stared_techsaved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technique",
            name="component",
        ),
        migrations.AddField(
            model_name="technique",
            name="component",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="techniques_app.component",
            ),
            preserve_default=False,
        ),
    ]
