# Generated by Django 5.0.6 on 2024-05-31 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_comunityprofile_userstatus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ComunityProfile",
            new_name="CommunityProfile",
        ),
    ]
