# Generated by Django 5.1.1 on 2024-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_userstatus_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inter", "No interested"),
                            ("use", "Interested but not using it"),
                            ("no", "No reasons"),
                            ("info", "Worried for my privacy"),
                            ("fit", "Theory does not fit me"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("confirm", models.BooleanField()),
            ],
        ),
    ]
