# Generated by Django 5.1.1 on 2024-10-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_deleteaccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userstatus",
            options={
                "permissions": [
                    ("can_dive", "User can access dive section"),
                    ("is_premium", "User have full access of the site"),
                    ("is_therapist", "User can access therapist areas"),
                    ("is_client", "User can access client areas"),
                    ("is_trainee", "User can access trainee areas"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="userstatus",
            name="therapist",
        ),
        migrations.AddField(
            model_name="userstatus",
            name="diver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userstatus",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("therapist", "I am a Therapist"),
                    ("client", "I am Client"),
                    ("trainee", "I am a Trainee"),
                ],
                default="therapist",
                max_length=30,
            ),
        ),
    ]
