# Generated by Django 5.1.1 on 2024-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_alter_userstatus_options_remove_userstatus_therapist_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userstatus",
            options={
                "permissions": [
                    ("can_dive", "User can access dive section"),
                    ("is_therapist", "User can access therapist areas"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="userstatus",
            name="premium",
        ),
        migrations.RemoveField(
            model_name="userstatus",
            name="user_type",
        ),
        migrations.AddField(
            model_name="userstatus",
            name="therapist",
            field=models.CharField(default=False),
        ),
    ]
