# Generated by Django 5.1.1 on 2024-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_alter_userstatus_options_remove_userstatus_premium_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatus",
            name="therapist",
            field=models.BooleanField(default=False),
        ),
    ]
