# Generated by Django 5.1.1 on 2024-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_communityprofile_user_alter_userstatus_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deleteaccount",
            name="reason",
            field=models.CharField(
                choices=[
                    ("no_inter", "No interested"),
                    ("no_use", "Interested but not using it"),
                    ("no_reason", "No reasons"),
                    ("privacy", "Worried for my privacy"),
                    ("no_fit", "Theory does not fit me"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
