# Generated by Django 5.1.1 on 2024-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dive_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shadow",
            name="text_care_plan",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="shadow",
            name="text_furor_curandis",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="shadow",
            name="text_opossite_style",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="shadow",
            name="text_opposite_sex",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="shadow",
            name="text_oppossite_elements",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="shadow",
            name="text_transf_characters",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="shadow",
            name="text_trauma_history",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="shadow",
            name="text_trauma_triggers",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
