# Generated by Django 5.1.3 on 2024-12-13 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dive_app", "0003_alter_creation_text_concepts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssembleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default=None, max_length=500)),
                ("position", models.TextField(blank=True, default="", null=True)),
                (
                    "reality_assumptions",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("change", models.TextField(blank=True, default="", null=True)),
                ("relational", models.TextField(blank=True, default="", null=True)),
                ("ontology", models.TextField(blank=True, default="", null=True)),
                ("knowledge", models.TextField(blank=True, default="", null=True)),
                ("traditions", models.TextField(blank=True, default="", null=True)),
                ("components", models.TextField(blank=True, default="", null=True)),
                ("clients", models.TextField(blank=True, default="", null=True)),
                ("simple_words", models.TextField(blank=True, default="", null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AssembleModel",
            },
        ),
    ]
