# Generated by Django 4.2.10 on 2024-05-07 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Personal_Style",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "follower_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "propositive_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "challenger_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "acceptant_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "intensive_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "extensive_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "divider_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "containment_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "becoming_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "development_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "individuation_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "belonging_1",
                    models.IntegerField(
                        choices=[
                            (-5, "I feel contrary"),
                            (1, "It sound ok?"),
                            (3, "I feel a little close to it"),
                            (6, "I agree with the premise"),
                            (10, "I feel it is my style"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("shadow", models.TextField(default="")),
                ("traditions", models.TextField(default="")),
                ("authors", models.TextField(default="")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="between_app.contentgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentgroup",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="between_app.personal_style",
            ),
        ),
    ]
