# Generated by Django 4.2.8 on 2024-02-22 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal_Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follower_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "propositive_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "challenger_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "acceptant_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "intensive_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "extensive_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "divider_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "containment_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "becoming_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "development_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "individuation_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "belonging_1",
                    models.IntegerField(
                        choices=[
                            (-1, "I reject"),
                            (1, "I feel a little close"),
                            (2, "I agree"),
                            (3, "I feel commited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
