# Generated by Django 4.2.13 on 2024-05-23 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personal_style",
            options={"get_latest_by": "updated_at"},
        ),
    ]
