# Generated by Django 4.2.8 on 2024-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal_style",
            name="acceptant_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="becoming_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="belonging_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="challenger_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="containment_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="development_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="divider_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="extensive_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="follower_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="individuation_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="intensive_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="propositive_1",
            field=models.IntegerField(
                choices=[
                    (-1, "I reject"),
                    (1, "I feel a little close"),
                    (3, "I agree"),
                    (7, "I feel commited"),
                ],
                default=1,
            ),
        ),
    ]
