# Generated by Django 5.0.6 on 2024-07-15 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0002_alter_personal_style_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Personal_Style",
            new_name="PersonalStyle",
        ),
        migrations.RenameModel(
            old_name="PS_group",
            new_name="PersonalStyleGroup",
        ),
        migrations.RenameModel(
            old_name="PS_Section",
            new_name="PersonalStyleSection",
        ),
    ]
