# Generated by Django 4.2.10 on 2024-02-27 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0002_alter_personal_style_acceptant_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal_style",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
