# Generated by Django 4.2.10 on 2024-02-27 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0003_alter_personal_style_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal_style",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personal_style",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
