# Generated by Django 4.2.10 on 2024-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0004_personal_style_created_at_personal_style_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal_style",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
