# Generated by Django 4.2.10 on 2024-02-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0005_alter_personal_style_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="acceptant_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="becoming_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="belonging_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="challenger_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="containment_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="development_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="divider_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="extensive_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="follower_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="individuation_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="intensive_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="propositive_1",
            field=models.IntegerField(
                choices=[
                    (-5, "I feel contrary"),
                    (1, "It sound ok?"),
                    (3, "I feel a little close to it"),
                    (6, "I agree with the premise"),
                    (10, "I feel it is my style"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="ContentProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("shadow", models.TextField(default="")),
                ("traditions", models.TextField(default="")),
                ("authors", models.TextField(default="")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="between_app.contentgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentgroup",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="between_app.contentsection",
            ),
        ),
    ]
