# Generated by Django 4.2.8 on 2024-03-06 16:47

from django.db import migrations
from ..models import ContentGroup,ContentSection,ContentProperties
from ..content import PositionContent, PathContent, TraditionContent

def create_content():
    ContentSection.objects.create(name='Personal_Profile')
    ContentGroup.objects.create(name='position')
    ContentGroup.objects.create(name='path')
    ContentGroup.objects.create(name='tradition')

    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='position').pk,
        name = PositionContent.compassionate.name,
        description = PositionContent.compassionate.description,
        shadow = PositionContent.compassionate.shadow,
        traditions = PositionContent.compassionate.tradition,
        authors = PositionContent.compassionate.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='position').pk,
        name = PositionContent.playful.name,
        description = PositionContent.playful.description,
        shadow = PositionContent.playful.shadow,
        traditions = PositionContent.playful.tradition,
        authors = PositionContent.playful.authors,
        )    
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='position').pk,
        name = PositionContent.inquisitive.name,
        description = PositionContent.inquisitive.description,
        shadow = PositionContent.inquisitive.shadow,
        traditions = PositionContent.inquisitive.tradition,
        authors = PositionContent.inquisitive.authors,
        )  
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='position').pk,
        name = PositionContent.changer.name,
        description = PositionContent.changer.description,
        shadow = PositionContent.changer.shadow,
        traditions = PositionContent.changer.tradition,
        authors = PositionContent.changer.authors,
        )  

    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='path').pk,
        name = PathContent.dreamer.name,
        description = PathContent.dreamer.description,
        shadow = PathContent.dreamer.shadow,
        traditions = PathContent.dreamer.tradition,
        authors = PathContent.dreamer.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='path').pk,
        name = PathContent.sage.name,
        description = PathContent.sage.description,
        shadow = PathContent.sage.shadow,
        traditions = PathContent.sage.tradition,
        authors = PathContent.sage.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='path').pk,
        name = PathContent.explorer.name,
        description = PathContent.explorer.description,
        shadow = PathContent.explorer.shadow,
        traditions = PathContent.explorer.tradition,
        authors = PathContent.explorer.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='path').pk,
        name = PathContent.carer.name,
        description = PathContent.carer.description,
        shadow = PathContent.carer.shadow,
        traditions = PathContent.carer.tradition,
        authors = PathContent.carer.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='tradition').pk,
        name = TraditionContent.artist.name,
        description = TraditionContent.artist.description,
        shadow = TraditionContent.artist.shadow,
        traditions = TraditionContent.artist.tradition,
        authors = TraditionContent.artist.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='tradition').pk,
        name = TraditionContent.warrior.name,
        description = TraditionContent.warrior.description,
        shadow = TraditionContent.warrior.shadow,
        traditions = TraditionContent.warrior.tradition,
        authors = TraditionContent.warrior.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='tradition').pk,
        name = TraditionContent.lider.name,
        description = TraditionContent.lider.description,
        shadow = TraditionContent.lider.shadow,
        traditions = TraditionContent.lider.tradition,
        authors = TraditionContent.lider.authors,
        )
    ContentProperties.objects.create(
        group = ContentGroup.objects.get(name='tradition').pk,
        name = TraditionContent.coach.name,
        description = TraditionContent.coach.description,
        shadow = TraditionContent.coach.shadow,
        traditions = TraditionContent.coach.tradition,
        authors = TraditionContent.coach.authors,
        )
    


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0006_contentgroup_contentsection_and_more"), #name of app affected and last migration
    ]

    operations = [
        migrations.RunPython(create_content),
    ]
