# Generated by Django 5.1.3 on 2025-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0006_alter_bigtraditions_user_alter_components_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalstyle",
            name="therapist",
            field=models.BooleanField(default=True),
        ),
    ]
