# Generated by Django 4.2.8 on 2024-03-06 16:47

from django.db import migrations
from ..content import Content
from django.apps import apps

def create_content():
    try: 
        ContentGroup = apps.get_model('between_app', 'ContentGroup')
        ContentProperties = apps.get_model('between_app', 'ContentProperties')
        Personal_Style = apps.get_model('between_app', 'Personal_Style')
    except: LookupError

    Position = ContentGroup.objects.create(name='position',section=Personal_Style)
    Path = ContentGroup.objects.create(name='path',section=Personal_Style)
    Tradition = ContentGroup.objects.create(name='tradition',section=Personal_Style)

    add = {Position:Content.position,
         Path:Content.path,
         Tradition:Content.tradition}
    for a, i in add.values:
       ContentProperties.objects.create(
            group = a,
            name = i['name'],
            description = i['description'],
            shadow = i['shadow'],
            traditions = i['traditions'],
            authors = i['authors'],
            )




class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0006_contentgroup_contentsection_and_more"), #name of app affected and last migration
    ]

    operations = [
        migrations.RunPython(create_content),
    ]
