# Generated by Django 4.2.8 on 2024-03-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0006_contentgroup_contentsection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentgroup",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="between_app.personal_style",
            ),
        ),
        migrations.DeleteModel(
            name="ContentSection",
        ),
    ]
