# Generated by Django 4.2.13 on 2024-05-24 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0002_alter_personal_style_options"),
        ("between_app", "0007_alter_contentgroup_section_delete_contentsection"),
    ]

    operations = []
