# Generated by Django 5.1.5 on 2025-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0008_alter_personalstyle_acceptant_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bigtraditions",
            name="constructive",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="bigtraditions",
            name="cybernetic",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="bigtraditions",
            name="hemeneutic",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="bigtraditions",
            name="participatory",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="bigtraditions",
            name="phenomenological",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="bigtraditions",
            name="scientific",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="bigtraditions",
            name="spiritual",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="antropology",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="arts",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="belonging",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="body",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="dreaming",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="expression",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="family",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="feelings",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="individuation",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="narrative",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="philosophy",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="politics",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="re_prog",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="relational",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="roles",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="setup",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="sex_gender",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="spiritual",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="subliminal",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="subparts",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="systems",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="thoughts",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="transOb",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="values",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="components",
            name="worldview",
            field=models.IntegerField(
                default=0, help_text="Training until the center, forward expertise"
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="acceptant_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="becoming_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="belonging_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="challenger_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="containment_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="development_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="divider_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="extensive_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="follower_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="individuation_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="intensive_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
        migrations.AlterField(
            model_name="personalstyle",
            name="propositive_1",
            field=models.IntegerField(
                default=50,
                help_text="Move right for support of the statement, and left for disagreement",
            ),
        ),
    ]
