# Generated by Django 4.2.13 on 2024-05-24 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0008_merge_20240524_1727"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentproperties",
            name="group",
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="ContentGroup",
        ),
        migrations.DeleteModel(
            name="ContentProperties",
        ),
    ]
