# Generated by Django 6.0.4 on 2026-07-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0009_alter_bigtraditions_constructive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalstylegroup",
            name="is_for_therapist",
            field=models.BooleanField(default=True),
        ),
    ]
