# Generated by Django 4.2.13 on 2024-05-28 10:34

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0009_remove_contentproperties_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PS_Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PS_group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group", models.CharField(default="", max_length=20)),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/uploads", location="static/"
                        ),
                        upload_to="",
                    ),
                ),
                ("description", models.TextField(default="")),
                ("shadow", models.TextField(default="")),
                ("traditions", models.TextField(default="")),
                ("authors", models.TextField(default="")),
                (
                    "section",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="between_app.ps_section",
                    ),
                ),
            ],
        ),
    ]
