# Generated by Django 5.0.6 on 2024-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0011_emailsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ps_group",
            name="image_path",
            field=models.CharField(default="", max_length=300),
        ),
    ]
