# Generated by Django 5.0.6 on 2024-06-01 21:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0012_ps_group_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ps_group",
            name="image",
            field=models.ImageField(
                height_field="300px",
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads", location="static/"
                ),
                upload_to="",
                width_field="200px",
            ),
        ),
    ]
