# Generated by Django 5.0.6 on 2024-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0015_alter_ps_group_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ps_group",
            name="image_path",
        ),
        migrations.AlterField(
            model_name="ps_group",
            name="image",
            field=models.CharField(default="", max_length=300),
        ),
    ]
