# Generated by Django 5.0.6 on 2024-06-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0017_alter_bigtraditions_cybernetic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigtraditions",
            name="constructive",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bigtraditions",
            name="participatory",
            field=models.IntegerField(default=1),
        ),
    ]
