# Generated by Django 5.0.6 on 2024-06-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("between_app", "0018_bigtraditions_constructive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal_style",
            name="acceptant_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="becoming_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="belonging_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="challenger_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="containment_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="development_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="divider_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="extensive_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="follower_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="individuation_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="intensive_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personal_style",
            name="propositive_1",
            field=models.IntegerField(default=1),
        ),
    ]
