# Generated by Django 6.0.4 on 2026-04-15 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("cards_app", "0001_initial"),
        ("cards_app", "0002_cardtype_bg_color"),
        ("cards_app", "0003_alter_card_image_alter_card_name"),
        ("cards_app", "0004_card_alt_text"),
        ("cards_app", "0005_card_created_card_modified"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("bg_color", models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DeckVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("text", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "card_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cards_app.cardtype",
                    ),
                ),
                (
                    "deck_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards_app.deckversion",
                    ),
                ),
                ("alt_text", models.TextField(blank=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
