# Generated by Django 6.0 on 2026-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtype",
            name="bg_color",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
