# Generated by Django 6.0 on 2026-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_app", "0002_cardtype_bg_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
