# Generated by Django 6.0 on 2026-04-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_app", "0003_alter_card_image_alter_card_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="alt_text",
            field=models.TextField(blank=True),
        ),
    ]
