# Generated by Django 6.0 on 2026-04-15 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_app", "0004_card_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
