# Generated by Django 6.0.4 on 2026-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards_app", "0001_squashed_0005_card_created_card_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cardtype",
            name="bg_color",
            field=models.CharField(max_length=100),
        ),
    ]
