# Generated by Django 4.2.13 on 2024-05-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
